In [11]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\OrdersDtaa.xlsx")
ds.isnull().sum()/ds.shape[0]*100
ds.shape

(1952, 8)

In [15]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
ds.isnull().sum()/ds.shape[0]*100

Row ID                    0.000000
Order Priority            0.000000
Discount                  0.000000
Unit Price                0.000000
Shipping Cost             0.000000
NetUnitPrice              0.000000
Customer ID               0.000000
Customer Name             0.000000
Ship Mode                 0.000000
Customer Segment          0.000000
Product Category          0.000000
Product Sub-Category      0.000000
Product Container         0.000000
Product Name              0.000000
Product Base Margin       0.819672
SellUnitPrice             0.000000
Country                   0.000000
Region                    0.000000
State or Province         0.000000
City                      0.000000
Postal Code               0.000000
Order Date                0.000000
Ship Date                 0.000000
Profit                    0.000000
Quantity ordered new      0.000000
Sales                     0.000000
Order ID                  0.000000
NetAmount                 0.000000
NetProfit                 0.000000
Loss                      0.000000
Profit.1                  0.000000
Unnamed: 31              99.846311
Unnamed: 32              99.795082
Unnamed: 33              99.795082
Unnamed: 34             100.000000
Unnamed: 35              99.897541
Unnamed: 36              99.897541
dtype: float64

In [27]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
ds.isnull().sum().sum()/(ds.shape[0]*ds.shape[1])*100
ds.shape

ds.fillna("XY")
ds.head(20)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,NetUnitPrice,Customer ID,Customer Name,Ship Mode,Customer Segment,...,NetAmount,NetProfit,Loss,Profit.1,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,20847,High,0.01,2.84,0.93,3.7416,3,Bonnie Potter,Express Air,Corporate,...,23.048256,18.2400,0.0000,18.2400,NaN,NaN,NaN,NaN,NaN,NaN
1,20228,Not Specified,0.02,500.98,26.00,516.9604,5,Ronnie Proctor,Delivery Truck,Home Office,...,9925.639680,52684.3980,0.0000,52684.3980,NaN,Order Count,Profit,NaN,NaN,NaN
2,21776,Critical,0.06,9.48,7.29,16.2012,11,Marcus Dunlap,Regular Air,Home Office,...,516.818280,-1183.8112,-1183.8112,0.0000,Office Supplies,14287,2153026.324232,NaN,Loss,2.671047e+06
3,24844,Medium,0.09,78.69,19.99,91.5979,14,Gwendolyn F Tyson,Regular Air,Small Business,...,2095.759952,12855.5280,0.0000,12855.5280,Furniture,5063,1639308.639335,NaN,Profit,9.226989e+06
4,24846,Medium,0.08,3.28,2.31,5.3276,14,Gwendolyn F Tyson,Regular Air,Small Business,...,58.177392,-168.2100,-168.2100,0.0000,Technology,5918,2763607.332456,NaN,NaN,NaN
5,24847,Medium,0.05,3.28,4.20,7.3160,14,Gwendolyn F Tyson,Regular Air,Small Business,...,45.651840,-148.1200,-148.1200,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
6,24848,Medium,0.05,3.58,1.63,5.0310,14,Gwendolyn F Tyson,Regular Air,Small Business,...,27.368640,-2.8400,-2.8400,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
7,18181,Critical,0.00,4.42,4.99,9.4100,15,Timothy Reese,Regular Air,Small Business,...,90.900600,-418.7400,-418.7400,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
8,20925,Medium,0.01,35.94,6.66,42.2406,15,Timothy Reese,Regular Air,Small Business,...,591.368400,2618.7570,0.0000,2618.7570,NaN,NaN,NaN,NaN,NaN,NaN
9,26267,High,0.04,2.98,1.58,4.4408,16,Sarah Ramsey,Regular Air,Small Business,...,37.036272,15.7800,0.0000,15.7800,NaN,NaN,NaN,NaN,NaN,NaN
10,26268,High,0.05,115.99,2.50,112.6905,16,Sarah Ramsey,Regular Air,Small Business,...,1746.702750,6527.3310,0.0000,6527.3310,NaN,NaN,NaN,NaN,NaN,NaN
11,23890,High,0.05,26.48,6.93,32.0860,18,Laurie Hanna,Regular Air,Small Business,...,812.738380,5346.1821,0.0000,5346.1821,NaN,NaN,NaN,NaN,NaN,NaN
12,24063,Not Specified,0.07,12.99,9.44,21.5207,19,Jim Rodgers,Regular Air,Small Business,...,538.447914,-2063.5182,-2063.5182,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
13,5890,High,0.05,26.48,6.93,32.0860,21,Tony Wilkins Winters,Regular Air,Small Business,...,3346.569800,26906.6000,0.0000,26906.6000,NaN,NaN,NaN,NaN,NaN,NaN
14,6062,Not Specified,0.08,5.00,3.39,7.9900,21,Tony Wilkins Winters,Regular Air,Small Business,...,634.885400,-1014.4200,-1014.4200,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
15,6063,Not Specified,0.07,12.99,9.44,21.5207,21,Tony Wilkins Winters,Regular Air,Small Business,...,2123.877883,-8139.4329,-8139.4329,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
16,20631,High,0.06,55.48,14.30,66.4512,24,Edna Thomas,Regular Air,Corporate,...,91.038144,-28.2968,-28.2968,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
17,20632,High,0.02,1.68,1.57,3.2164,24,Edna Thomas,Regular Air,Corporate,...,5.114076,-5.3072,-5.3072,0.0000,NaN,NaN,NaN,NaN,NaN,NaN
18,23967,Not Specified,0.04,4.14,6.60,10.5744,27,Guy Gallagher,Regular Air,Corporate,...,189.070272,106.7280,0.0000,106.7280,NaN,NaN,NaN,NaN,NaN,NaN
19,23509,High,0.08,34.99,7.73,39.9208,32,Matthew Berman,Regular Air,Corporate,...,825.162936,1880.9700,0.0000,1880.9700,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
ds.isnull().sum().sum()/(ds.shape[0]*ds.shape[1])*100

ds.fillna(method="ffill",axis=1).head(20)

C:\Users\dell\AppData\Local\Temp\ipykernel_3992\3995899702.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ds.fillna(method="ffill",axis=1).head(20)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,NetUnitPrice,Customer ID,Customer Name,Ship Mode,Customer Segment,...,NetAmount,NetProfit,Loss,Profit.1,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,20847,High,0.01,2.84,0.93,3.7416,3,Bonnie Potter,Express Air,Corporate,...,23.048256,18.24,0.0,18.24,18.24,18.24,18.24,18.24,18.24,18.24
1,20228,Not Specified,0.02,500.98,26.0,516.9604,5,Ronnie Proctor,Delivery Truck,Home Office,...,9925.63968,52684.398,0.0,52684.398,52684.398,Order Count,Profit,Profit,Profit,Profit
2,21776,Critical,0.06,9.48,7.29,16.2012,11,Marcus Dunlap,Regular Air,Home Office,...,516.81828,-1183.8112,-1183.8112,0.0,Office Supplies,14287,2153026.324232,2153026.324232,Loss,2671046.802551
3,24844,Medium,0.09,78.69,19.99,91.5979,14,Gwendolyn F Tyson,Regular Air,Small Business,...,2095.759952,12855.528,0.0,12855.528,Furniture,5063,1639308.639335,1639308.639335,Profit,9226989.098573
4,24846,Medium,0.08,3.28,2.31,5.3276,14,Gwendolyn F Tyson,Regular Air,Small Business,...,58.177392,-168.21,-168.21,0.0,Technology,5918,2763607.332456,2763607.332456,2763607.332456,2763607.332456
5,24847,Medium,0.05,3.28,4.2,7.316,14,Gwendolyn F Tyson,Regular Air,Small Business,...,45.65184,-148.12,-148.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,24848,Medium,0.05,3.58,1.63,5.031,14,Gwendolyn F Tyson,Regular Air,Small Business,...,27.36864,-2.84,-2.84,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,18181,Critical,0.0,4.42,4.99,9.41,15,Timothy Reese,Regular Air,Small Business,...,90.9006,-418.74,-418.74,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,20925,Medium,0.01,35.94,6.66,42.2406,15,Timothy Reese,Regular Air,Small Business,...,591.3684,2618.757,0.0,2618.757,2618.757,2618.757,2618.757,2618.757,2618.757,2618.757
9,26267,High,0.04,2.98,1.58,4.4408,16,Sarah Ramsey,Regular Air,Small Business,...,37.036272,15.78,0.0,15.78,15.78,15.78,15.78,15.78,15.78,15.78
10,26268,High,0.05,115.99,2.5,112.6905,16,Sarah Ramsey,Regular Air,Small Business,...,1746.70275,6527.331,0.0,6527.331,6527.331,6527.331,6527.331,6527.331,6527.331,6527.331
11,23890,High,0.05,26.48,6.93,32.086,18,Laurie Hanna,Regular Air,Small Business,...,812.73838,5346.1821,0.0,5346.1821,5346.1821,5346.1821,5346.1821,5346.1821,5346.1821,5346.1821
12,24063,Not Specified,0.07,12.99,9.44,21.5207,19,Jim Rodgers,Regular Air,Small Business,...,538.447914,-2063.5182,-2063.5182,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,5890,High,0.05,26.48,6.93,32.086,21,Tony Wilkins Winters,Regular Air,Small Business,...,3346.5698,26906.6,0.0,26906.6,26906.6,26906.6,26906.6,26906.6,26906.6,26906.6
14,6062,Not Specified,0.08,5.0,3.39,7.99,21,Tony Wilkins Winters,Regular Air,Small Business,...,634.8854,-1014.42,-1014.42,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,6063,Not Specified,0.07,12.99,9.44,21.5207,21,Tony Wilkins Winters,Regular Air,Small Business,...,2123.877883,-8139.4329,-8139.4329,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,20631,High,0.06,55.48,14.3,66.4512,24,Edna Thomas,Regular Air,Corporate,...,91.038144,-28.2968,-28.2968,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,20632,High,0.02,1.68,1.57,3.2164,24,Edna Thomas,Regular Air,Corporate,...,5.114076,-5.3072,-5.3072,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,23967,Not Specified,0.04,4.14,6.6,10.5744,27,Guy Gallagher,Regular Air,Corporate,...,189.070272,106.728,0.0,106.728,106.728,106.728,106.728,106.728,106.728,106.728
19,23509,High,0.08,34.99,7.73,39.9208,32,Matthew Berman,Regular Air,Corporate,...,825.162936,1880.97,0.0,1880.97,1880.97,1880.97,1880.97,1880.97,1880.97,1880.97

In [44]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
ds.isnull().sum().sum()/(ds.shape[0]*ds.shape[1])*100

ds["Order Priority"].fillna(method="ffill").head(20)

C:\Users\dell\AppData\Local\Temp\ipykernel_3992\344670593.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ds["Order Priority"].fillna(method="ffill").head(20)

0              High
1     Not Specified
2          Critical
3            Medium
4            Medium
5            Medium
6            Medium
7          Critical
8            Medium
9              High
10             High
11             High
12    Not Specified
13             High
14    Not Specified
15    Not Specified
16             High
17             High
18    Not Specified
19             High
Name: Order Priority, dtype: object

In [56]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
ds["Order Priority"].mode()[0]
ds["Order Priority"].fillna(ds["Order Priority"].mode()[0])
ds.select_dtypes(include="object").columns

Index(['Order Priority', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Country', 'Region', 'State or Province', 'City',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 35'],
      dtype='object')

In [13]:
import pandas as pd 
ds =pd.read_excel(r"C:\Users\dell\Downloads\P6-SuperStoreUS-2015.xlsx")
for a in ds.select_dtypes(include="object").columns:
    ds[a]=ds[a].fillna(ds[a].mode()[0])
for a in ds.select_dtypes(include="int64").columns:
    ds[a]=ds[a].fillna(ds[a].mean())

C:\Users\dell\AppData\Local\Temp\ipykernel_4308\2016488187.py:4: UserWarning: Unable to sort modes: '<' not supported between instances of 'int' and 'str'
  ds[a]=ds[a].fillna(ds[a].mode()[0])
C:\Users\dell\AppData\Local\Temp\ipykernel_4308\2016488187.py:4: UserWarning: Unable to sort modes: '<' not supported between instances of 'float' and 'str'
  ds[a]=ds[a].fillna(ds[a].mode()[0])